apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-infra
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/crossplane
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-manifests
  healthChecks:
    - apiVersion: apiextensions.crossplane.io/v1
      kind: CompositeResourceDefinition
      name: xpostgresqlinstances.database.platform.io